/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Jasmitsingh.glb
*/

import React, { useEffect, useRef, useMemo } from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useFBX, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Avatar(props) {
    const model = useRef();

    const { scene } = useGLTF('models/Jasmitsingh.glb')
    const clone = useMemo(() => SkeletonUtils.clone(scene), [scene])
    const { nodes, materials } = useGraph(clone)

    // Load ALL animations
    const { animations: typingAnimation } = useFBX('/animations/Typing.fbx')
    const { animations: standingAnimation } = useFBX('/animations/Standing Idle.fbx')
    const { animations: fallingAnimation } = useFBX('/animations/Falling Idle.fbx')
    const { animations: callingAnimation } = useFBX('/animations/calling.fbx')
    const { animations: wavingAnimation } = useFBX('/animations/Waving.fbx')
    const { animations: walkingAnimation } = useFBX('/animations/Walking.fbx')
    const { animations: openAnimation } = useFBX('/animations/open.fbx')
    const { animations: sitToStandAnimation } = useFBX('/animations/Sit To Stand.fbx')

    // Memoize animations setup
    const allAnimations = useMemo(() => {
        if (!typingAnimation[0] || !standingAnimation[0] || !fallingAnimation[0] || !callingAnimation[0] || !wavingAnimation[0] || !walkingAnimation[0] || !openAnimation[0] || !sitToStandAnimation[0]) return []

        typingAnimation[0].name = "Typing"
        standingAnimation[0].name = "Standing"
        fallingAnimation[0].name = "Falling"
        callingAnimation[0].name = "Calling"
        wavingAnimation[0].name = "Waving"
        walkingAnimation[0].name = "Walking"
        openAnimation[0].name = "Open"
        sitToStandAnimation[0].name = "SitToStand"

        return [
            typingAnimation[0], standingAnimation[0], fallingAnimation[0],
            callingAnimation[0], wavingAnimation[0], walkingAnimation[0],
            openAnimation[0], sitToStandAnimation[0]
        ]
    }, [typingAnimation, standingAnimation, fallingAnimation, callingAnimation, wavingAnimation, walkingAnimation, openAnimation, sitToStandAnimation])

    const { actions } = useAnimations(allAnimations, model)

    useEffect(() => {
        const currentAnimation = props.animation || "Standing"
        const action = actions[currentAnimation]
        if (action) {
            action.reset().fadeIn(0.5).play()
            return () => {
                if (action.fadeOut) action.fadeOut(0.5)
            }
        }
    }, [props.animation, actions])

    return (
        <group {...props} ref={model} dispose={null}>
            <group rotation-x={-Math.PI / 2}>
                <primitive object={nodes.Hips} />
                <skinnedMesh castShadow receiveShadow geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
                <skinnedMesh castShadow receiveShadow geometry={nodes.Wolf3D_Glasses.geometry} material={materials.Wolf3D_Glasses} skeleton={nodes.Wolf3D_Glasses.skeleton} />
                <skinnedMesh castShadow receiveShadow geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
                <skinnedMesh castShadow receiveShadow geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
                <skinnedMesh castShadow receiveShadow geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
                <skinnedMesh castShadow receiveShadow name="EyeLeft" geometry={nodes.EyeLeft.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeLeft.skeleton} morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary} morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences} />
                <skinnedMesh castShadow receiveShadow name="EyeRight" geometry={nodes.EyeRight.geometry} material={materials.Wolf3D_Eye} skeleton={nodes.EyeRight.skeleton} morphTargetDictionary={nodes.EyeRight.morphTargetDictionary} morphTargetInfluences={nodes.EyeRight.morphTargetInfluences} />
                <skinnedMesh castShadow receiveShadow name="Wolf3D_Beard" geometry={nodes.Wolf3D_Beard.geometry} material={materials.Wolf3D_Beard} skeleton={nodes.Wolf3D_Beard.skeleton} morphTargetDictionary={nodes.Wolf3D_Beard.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Beard.morphTargetInfluences} />
                <skinnedMesh castShadow receiveShadow name="Wolf3D_Head" geometry={nodes.Wolf3D_Head.geometry} material={materials.Wolf3D_Skin} skeleton={nodes.Wolf3D_Head.skeleton} morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences} />
                <skinnedMesh castShadow receiveShadow name="Wolf3D_Teeth" geometry={nodes.Wolf3D_Teeth.geometry} material={materials.Wolf3D_Teeth} skeleton={nodes.Wolf3D_Teeth.skeleton} morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary} morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences} />
            </group>
        </group>
    )
}

useGLTF.preload('models/Jasmitsingh.glb')
useFBX.preload('/animations/Typing.fbx')
useFBX.preload('/animations/Standing Idle.fbx')
useFBX.preload('/animations/Falling Idle.fbx')
useFBX.preload('/animations/calling.fbx')
useFBX.preload('/animations/Waving.fbx')
useFBX.preload('/animations/Walking.fbx')
useFBX.preload('/animations/open.fbx')
useFBX.preload('/animations/Sit To Stand.fbx')
