/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scene.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const group = React.useRef()

  const { nodes, materials } = useGLTF('models/scene.glb')
  return (
    <group ref={group} {...props} dispose={null}>
    <group name="Scene">
      <group name="Plamtree" position={[0.455, 0.26, 0]}>
        <mesh name="Environment_PalmTree_1" geometry={nodes.Environment_PalmTree_1.geometry} material={materials['Atlas.001']} position={[1.737, -0.202, -2.274]} scale={100} />
      </group>
      <group name="FlowerPlot" position={[0, 0.093, 0]}>
        <group name="Pot_Plant" position={[-2.58, 0.137, -2.299]} scale={[294.849, 341.425, 388.231]}>
          <mesh name="Pot_Plant001" geometry={nodes.Pot_Plant001.geometry} material={materials['mat24.002']} />
          <mesh name="Pot_Plant001_1" geometry={nodes.Pot_Plant001_1.geometry} material={materials['mat19.002']} />
          <mesh name="Pot_Plant001_2" geometry={nodes.Pot_Plant001_2.geometry} material={materials['mat21.002']} />
          <mesh name="Pot_Plant001_3" geometry={nodes.Pot_Plant001_3.geometry} material={materials['mat9.001']} />
          <mesh name="Pot_Plant001_4" geometry={nodes.Pot_Plant001_4.geometry} material={materials['mat20.001']} />
        </group>
      </group>
      <group name="Desktop" position={[0.139, -0.038, -2.438]} rotation={[-0.017, 0.75, 0.009]} scale={1.323}>
        <group name="Chair" position={[-1.383, 0.76, 0.307]} rotation={[-Math.PI / 2, 0, 1.643]} scale={[3.082, 3.082, 3.582]}>
          <mesh name="Chair001" geometry={nodes.Chair001.geometry} material={materials['Executive.001']} />
          <mesh name="Chair001_1" geometry={nodes.Chair001_1.geometry} material={materials['Executive__1.001']} />
          <mesh name="Chair001_2" geometry={nodes.Chair001_2.geometry} material={materials['Executive__2.001']} />
          <mesh name="Chair001_3" geometry={nodes.Chair001_3.geometry} material={materials['Executive__3.001']} />
        </group>
        <mesh name="Computer_mouse" geometry={nodes.Computer_mouse.geometry} material={materials['ComputerMouse_mat1.001']} position={[-0.566, 0.92, 0.599]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={2.93} />
        <group name="Computer_Screen" position={[-0.111, 0.919, 0.472]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={154.397}>
          <mesh name="Computer_Screen001" geometry={nodes.Computer_Screen001.geometry} material={materials['metalDark.001']} />
          <mesh name="Computer_Screen001_1" geometry={nodes.Computer_Screen001_1.geometry} material={materials['metal.001']} />
        </group>
        <group name="Cube002" position={[-0.111, 0.945, 1.079]} rotation={[-Math.PI / 2, 0, 3.106]} scale={[6.489, 9.4, 0.204]}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} />
          <mesh name="Cube001_1" geometry={nodes.Cube001_1.geometry} material={materials['Material.005']} />
        </group>
        <group name="Cylinder" position={[-0.094, 1.409, 0.484]} rotation={[0, -1.571, 0]} scale={6.449}>
          <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Grey.001']} />
          <mesh name="Cylinder001_1" geometry={nodes.Cylinder001_1.geometry} material={materials['Dark.001']} />
          <mesh name="Cylinder001_2" geometry={nodes.Cylinder001_2.geometry} material={materials['Blue.001']} />
          <mesh name="Cylinder001_3" geometry={nodes.Cylinder001_3.geometry} material={materials['Material.006']} />
        </group>
        <group name="Desk-V86Go2rlnq" position={[-0.778, 0.916, 0.419]} rotation={[-Math.PI, 1.571, 0]} scale={[10000, 9999.999, 9999.996]}>
          <mesh name="Desk-V86Go2rlnq001" geometry={nodes['Desk-V86Go2rlnq001'].geometry} material={materials['DarkWood.001']} />
          <mesh name="Desk-V86Go2rlnq001_1" geometry={nodes['Desk-V86Go2rlnq001_1'].geometry} material={materials['Wood.001']} />
        </group>
        <mesh name="Keyboard-aPwr5p1dluw" geometry={nodes['Keyboard-aPwr5p1dluw'].geometry} material={materials['Mat.001']} position={[-0.552, 0.919, 0.216]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.625} />
        <group name="Laptop_bag" position={[-0.556, 0.009, -0.604]} rotation={[-1.407, 0, -Math.PI]} scale={0}>
          <mesh name="Laptop_bag001" geometry={nodes.Laptop_bag001.geometry} material={materials['02___Default.001']} />
          <mesh name="Laptop_bag001_1" geometry={nodes.Laptop_bag001_1.geometry} material={materials['03___Default.001']} />
          <mesh name="Laptop_bag001_2" geometry={nodes.Laptop_bag001_2.geometry} material={materials['_crayfishdiffuse.001']} />
          <mesh name="Laptop_bag001_3" geometry={nodes.Laptop_bag001_3.geometry} material={materials['_crayfishdiffuse-2.001']} />
        </group>
        <group name="Light_Desk" position={[-0.135, 1.162, -0.245]} rotation={[-Math.PI / 2, 0, 2.301]} scale={[8561.476, 8561.474, 8561.473]}>
          <mesh name="Light_Desk001" geometry={nodes.Light_Desk001.geometry} material={materials['Black.003']} />
          <mesh name="Light_Desk001_1" geometry={nodes.Light_Desk001_1.geometry} material={materials['LightMetal.001']} />
          <mesh name="Light_Desk001_2" geometry={nodes.Light_Desk001_2.geometry} material={materials['White.001']} />
        </group>
        <mesh name="Mousepad002" geometry={nodes.Mousepad002.geometry} material={materials['Mousepad.002']} position={[-0.561, 0.919, 0.506]} scale={[1175.4, 15.541, 1400.88]} />
        <group name="Office_Phone002" position={[-0.328, 0.973, -0.086]} rotation={[Math.PI, 1.424, 0]} scale={626.776}>
          <mesh name="Office_Phone001" geometry={nodes.Office_Phone001.geometry} material={materials['Light grey.001']} />
          <mesh name="Office_Phone001_1" geometry={nodes.Office_Phone001_1.geometry} material={materials['Grey Plastic.001']} />
          <mesh name="Office_Phone001_2" geometry={nodes.Office_Phone001_2.geometry} material={materials['Screen.001']} />
          <mesh name="Office_Phone001_3" geometry={nodes.Office_Phone001_3.geometry} material={materials['Dark Grey Plastic.001']} />
        </group>
        <group name="System_unit001" position={[-0.4, 0.244, -0.257]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.162}>
          <mesh name="System_unit002" geometry={nodes.System_unit002.geometry} material={materials['lambert3SG.001']} />
          <mesh name="System_unit002_1" geometry={nodes.System_unit002_1.geometry} material={materials['initialShadingGroup.001']} />
        </group>
      </group>
      <group name="couch" position={[-0.416, 0, -0.09]} scale={0.5}>
        <group name="Couch_Medium1" position={[-4.17, 0, 3.526]} rotation={[-Math.PI / 2, 0, 1.602]} scale={100}>
          <mesh name="Couch_Medium1001" geometry={nodes.Couch_Medium1001.geometry} material={materials['Couch_Blue.001']} />
          <mesh name="Couch_Medium1001_1" geometry={nodes.Couch_Medium1001_1.geometry} material={materials['Black.004']} />
        </group>
      </group>
      <group name="Empty" position={[-0.756, 0.272, -0.97]} rotation={[3.113, 0.876, -3.09]} scale={1.323}>

      </group>
      <group name="Shelf" position={[-1.697, 3.028, -2.972]} rotation={[0, -0.519, 0]}>
        <mesh name="mesh301574616001" geometry={nodes.mesh301574616001.geometry} material={materials['mat14.001']} />
        <mesh name="mesh301574616001_1" geometry={nodes.mesh301574616001_1.geometry} material={materials['mat24.003']} />
        <mesh name="mesh301574616001_2" geometry={nodes.mesh301574616001_2.geometry} material={materials['mat21.003']} />
        <mesh name="mesh301574616001_3" geometry={nodes.mesh301574616001_3.geometry} material={materials['mat19.003']} />
        <mesh name="mesh301574616001_4" geometry={nodes.mesh301574616001_4.geometry} material={materials['mat8.001']} />
      </group>
      <group name="Plane" scale={3.248}>
        <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['floor.001']} />
        <mesh name="Plane003_1" geometry={nodes.Plane003_1.geometry} material={materials['Default.001']} />
        <mesh name="Plane003_2" geometry={nodes.Plane003_2.geometry} material={materials['wall.001']} />
      </group>
    </group>
  </group>

  )
}

useGLTF.preload('models/scene.glb')
